name = "speechless"
main = "src/index.js"
compatibility_date = "2023-09-01"
workers_dev = true

# Python configuration
compatibility_flags = ["python"]
python_args = ["--compile"]
python_pkg_reqs = ["fastapi", "httpx", "python-dotenv"]

[build]
command = ""  # No build command needed for Python

# Custom domain binding (uncomment when ready for production)
# routes = [
#   { pattern = "music.yourdomain.com", custom_domain = true }
# ]

# Environment variables
[vars]
DISCORD_CLIENT_ID = "1356319675717390507"
MAIN_URL = "localhost"
PORT = "8000"
DISCORD_REDIRECT_URI = "name = "speechless-web-ui"
main = "worker.py"
compatibility_date = "2023-09-01"
workers_dev = true

# Python configuration
compatibility_flags = ["python"]
python_args = ["--compile"]
python_pkg_reqs = ["fastapi", "httpx", "python-dotenv"]

[build]
command = ""  # No build command needed for Python

# Custom domain binding (uncomment when ready for production)
# routes = [
#   { pattern = "music.yourdomain.com", custom_domain = true }
# ]

# Environment variables
[vars]
DISCORD_CLIENT_ID = "1356319675717390507"
MAIN_URL = "localhost"
PORT = "8000"
DISCORD_REDIRECT_URI = "https://speechless.darshanisadev.workers.dev/oauth-callback"

# The following secrets should be set using `wrangler secret put`:
# - DISCORD_CLIENT_SECRET 
# - API_SECRET
# - SESSION_SECRET"

# The following secrets should be set using `wrangler secret put`:
# - DISCORD_CLIENT_SECRET 
# - API_SECRET
# - SESSION_SECRET
